name: custom_qr_generator
description: Custom QR generator for Flutter
version: 0.1.2
homepage: https://github.com/alexzhirkevich/custom-qr-generator-flutter

environment:
  sdk: ">=2.19.1 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  zxing_lib: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
